
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:h2-data.sql # 시작할때 실행시킬 script
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type: trace