spring:
  profiles:
    active: local # 기본 환경 선택
  datasource:
    data: classpath:data-h2.sql

# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type: trace
---