spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace